### ISSUE TITLE
linux_64 failures for 0.28.0 release

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/uvicorn-feedstock#113]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Several linux_64 builds here failed for the 0.28.0 release (see here https://github.com/conda-forge/uvicorn-feedstock/runs/22501723832). I'm not totally sure if those are just sporadic failures or not (it looks like they may be). Could someone restart CI here to see if that helps? 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by xhochy** [comment]
Clicked on rerun.

**Comment by jrbourbeau** [comment]
That seemed to do the trick -- I see new builds showing up in https://anaconda.org/conda-forge/uvicorn/files. Thanks @xhochy
